language: java
sudo: false
git:
  depth: 10
cache:
  directories:
  - "$HOME/.m2"
jdk:
  - openjdk11
deploy:
  provider: releases
  api_key:
    secure: UNFRh0vacAxhhkGddyzrtQGPkwkTdcXd555uW3eOMShjyNYU78cZn99YJHj8bKxrJzqmMS7JBPKiFOtRNpGIRFro+t4u75D7O7TBE27eXPW+HJGA7n0yLR3ri6OJyhuGCvA2TT6/a/2OpOOeWw1lXjpQW+4CwsOSCfSN2sZMH/GNswwVUfrP1Q8vSRDptSqlSi1SnXyPNWoTSZVvuc0VWF0aNwRr+uo9gvxWbBQZzIv4SaLQn89OvbzVLqsR9M5d9AS6C/i+tqvsrqgUWuU0Tpx30mtlqvodQ+6m/jXxijmE57gnS16rJCyqqkK0/4/Qx5M6SDe0xSDe1gLs7bMeOMutdzyy1dQYVucxWO3CIucjusoVdDZVZmrzI96Ei7CJCpernzaCp0e+yE8p9Hycqt6JekCZZW321X07Ld0sWsbFQm2xHvJgcGsRlq6jB3SWG4yrYYyk4GyTH+6oPv7IV8JCT6/ExGSagbdG18zDxNSjOfaB5/V+u10UzH7vfjVcZ7ETPRgRA5f++Jn/ITAtXjsS79TXXaHTT8EhbtvRfZApzXSwwGkQOKWk6idx6bMckPsfz7F5kIobvxPOjeRIKLMuReVSQdlD9BqrECVvOxTc5knx7bFHu8i4jef3EIgRxkKB+/gSh+Bugn5AdDTwg/MAnjcOuX1O+ku7EzuFAwQ=
  skip_cleanup: true
  file_glob: true
  file: target/koma-library-*.jar
  on:
    tags: true
    repo: druig/koma-library
