language: java
sudo: false
git:
  depth: 10
cache:
  directories:
  - "$HOME/.m2"
jdk:
  - openjdk11
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file: target/koma-library-*.jar
  on:
    tags: true
