language: java
sudo: false
git:
  depth: 10
cache:
  directories:
  - "$HOME/.m2"
jdk:
  - openjdk11
deploy:
  provider: releases
  api_key:
    secure: a13upSM6+sd67Jf2KXwC8kYrUaetykt/MdrqF7zYy+exe9kpm/Ll0sDx8G1cT/ou61fLOjB5stDnzCJz2cprnc1zAVO3wJPFGvt5ttDFxeSECjIyq7uQJyrHg2hqBi2AGeAtxMpHTQxZwVB3dwSdQJ0eyIU9puSzpT+n7+HDtsRhwddWooiiBUEOEgSgV9t02mlelz8RQ0+2fx3wsfMiyIew9Ncn/LoB9phfYpWbr6KqnuCFKbgdqTxb2pTPaIPmuZ/OXSf5LyKHaBhupEHt3Ujb5MaGpNd+/XrEM/Dll5P2eY42FeCrPIw1+gIsdOLkxme6Sf74GXeGYLHvrFTKerSuTrdzcJo+hwXQhfhbPu4InFIJzZH2ckFSZiThkb/3W277OrHtxjIB/kAl2zpcwybXBhlquQ2pYzCD7GT1oCVnIaRfW9VbzZun5By7okyYUAh2i+G9FlR/+ql4+BT011OtRHkz6NPzcixlzXWb7n2xy42riv8ZlqvSGuS3Zi14u8HIni4v7jtrL2HHzAuezIrDxhds0V64D6C/FWbYKLbcdIgKIUyNBjLBZf8d/piqfycqABSO9ETyyeJab95qC8uDy9x1SILOkwbx/dL9+cAgyQ6uzfExsIk8QoIKUtNuISi4zrE6w8+6nV14MdcXzYi/XgRX5SWcmGCYCVTtiUo=
  skip_cleanup: true
  file_glob: true
  file: target/koma-library-*.jar
  on:
    tags: true
    repo: druig/koma-library
